import {RecentQuizzes} from "@/app/components/recentquizzes";


export default function Main() {
    return (
        <div className={"mainContent"}>
            <h1>Recent activity</h1>
            <RecentQuizzes/>
            <hr/>
            <h1>Test your knowledge in these next topics</h1>
            <RecentQuizzes/>
            <hr/>
            <div>
                <button className={"indexButton"}><a href={"/uploading/"}>Create your own quiz
                    using AI!</a>
                </button>
            </div>
            <p>StudyHub can not guarantee that the questions generated by the AI are 100% accurate. We try to be as
                accurate as possible, however issues may still occur. We thank you for your understanding.</p>
        </div>
    );
}